#!/usr/bin/env python
"""Merge annotation fields (label/confidence/flags/notes) from the ChatGPT
annotation pass into the canonical blind CSV, by annotation_id.

We intentionally do NOT carry over the 'text' field from the hand-transcribed
source (that transcription had CSV-quoting issues with embedded quote marks
in some article texts). Instead we keep the already-correct 'text' column
from the existing canonical human_validation_pilot_300_blind.csv and only
overwrite the reviewer_* columns, keyed by annotation_id.
"""
import csv

BASE = r"C:\Users\P0039126\Downloads\תזה\final_project\data\annotation"

# annotation_id -> (reviewer_label, confidence, neutral_or_no_clear_narrative,
#                    ambiguous_flag, secondary_narrative, notes)
ANNOTATIONS = {
"HV001": ("", "3", "True", "False", "", ""),
"HV002": ("Left-wing", "3", "False", "False", "", ""),
"HV003": ("", "3", "True", "False", "", ""),
"HV004": ("Ukrainian", "3", "False", "False", "", ""),
"HV005": ("", "3", "True", "False", "", ""),
"HV006": ("Left-wing", "3", "False", "False", "", ""),
"HV007": ("", "3", "True", "False", "", ""),
"HV008": ("Left-wing", "3", "False", "False", "", ""),
"HV009": ("Russian", "3", "False", "False", "", ""),
"HV010": ("Western", "3", "False", "False", "", ""),
"HV011": ("", "3", "True", "False", "", ""),
"HV012": ("", "3", "True", "False", "", "Aggregator/placeholder-like text; no narrative framing."),
"HV013": ("Left-wing", "2", "False", "False", "", ""),
"HV014": ("", "3", "True", "False", "", ""),
"HV015": ("Resistance", "2", "False", "False", "", ""),
"HV016": ("Right-wing", "3", "False", "False", "", ""),
"HV017": ("", "3", "True", "False", "", "Commercial username-sale spam."),
"HV018": ("Resistance", "3", "False", "False", "", ""),
"HV019": ("Resistance", "3", "False", "False", "", ""),
"HV020": ("Western", "3", "False", "False", "", ""),
"HV021": ("", "3", "True", "False", "", "Greeting only; no narrative content."),
"HV022": ("", "3", "True", "False", "", ""),
"HV023": ("", "3", "True", "False", "", ""),
"HV024": ("Right-wing", "2", "False", "False", "", ""),
"HV025": ("Left-wing", "2", "False", "False", "", ""),
"HV026": ("Ukrainian", "3", "False", "False", "", ""),
"HV027": ("Right-wing", "2", "False", "False", "", ""),
"HV028": ("Left-wing", "3", "False", "False", "", ""),
"HV029": ("Resistance", "3", "False", "False", "", ""),
"HV030": ("Left-wing", "3", "False", "False", "", ""),
"HV031": ("Zionist", "3", "False", "False", "", ""),
"HV032": ("Ukrainian", "3", "False", "False", "", ""),
"HV033": ("", "3", "True", "False", "", "Advertisement/promotion; no relevant narrative framing."),
"HV034": ("Western", "3", "False", "False", "", ""),
"HV035": ("", "3", "True", "False", "", ""),
"HV036": ("Ukrainian", "2", "False", "False", "", ""),
"HV037": ("Western", "2", "False", "False", "", ""),
"HV038": ("Right-wing", "3", "False", "False", "", ""),
"HV039": ("", "3", "True", "False", "", ""),
"HV040": ("Left-wing", "1", "False", "True", "Right-wing", "Anti-war/anti-Trump framing could plausibly be read as left-wing or right-wing isolationism."),
"HV041": ("", "3", "True", "False", "", "URL-only row."),
"HV042": ("Ukrainian", "3", "False", "False", "", ""),
"HV043": ("", "3", "True", "False", "", ""),
"HV044": ("Ukrainian", "1", "False", "True", "Russian", "Conflict framing ('enemy targets') is present, but the text does not identify which side is speaking."),
"HV045": ("", "3", "True", "False", "", ""),
"HV046": ("Left-wing", "2", "False", "False", "", ""),
"HV047": ("Western", "2", "False", "False", "", ""),
"HV048": ("", "3", "True", "False", "", ""),
"HV049": ("Russian", "3", "False", "False", "", ""),
"HV050": ("Resistance", "3", "False", "False", "", ""),
"HV051": ("Western", "3", "False", "False", "", ""),
"HV052": ("Resistance", "3", "False", "False", "", ""),
"HV053": ("", "2", "True", "False", "", ""),
"HV054": ("Left-wing", "3", "False", "False", "", ""),
"HV055": ("Western", "2", "False", "False", "", ""),
"HV056": ("Zionist", "3", "False", "False", "", ""),
"HV057": ("Ukrainian", "3", "False", "False", "", ""),
"HV058": ("Resistance", "3", "False", "False", "", ""),
"HV059": ("Zionist", "3", "False", "False", "", ""),
"HV060": ("Western", "3", "False", "False", "", ""),
"HV061": ("", "3", "True", "False", "", ""),
"HV062": ("Russian", "2", "False", "False", "", ""),
"HV063": ("", "3", "True", "False", "", ""),
"HV064": ("", "2", "True", "False", "", ""),
"HV065": ("", "2", "True", "False", "", ""),
"HV066": ("Zionist", "2", "False", "False", "", ""),
"HV067": ("", "3", "True", "False", "", ""),
"HV068": ("Zionist", "3", "False", "False", "", ""),
"HV069": ("", "3", "True", "False", "", "URL-only row."),
"HV070": ("Russian", "3", "False", "False", "", ""),
"HV071": ("", "3", "True", "False", "", "Spam/placeholder text."),
"HV072": ("Left-wing", "3", "False", "False", "", ""),
"HV073": ("Zionist", "3", "False", "False", "", ""),
"HV074": ("", "2", "True", "False", "", ""),
"HV075": ("Zionist", "3", "False", "False", "", ""),
"HV076": ("Russian", "3", "False", "False", "", ""),
"HV077": ("", "2", "True", "False", "", ""),
"HV078": ("Zionist", "3", "False", "False", "", ""),
"HV079": ("Right-wing", "3", "False", "False", "", ""),
"HV080": ("Left-wing", "3", "False", "False", "", ""),
"HV081": ("Zionist", "3", "False", "False", "", ""),
"HV082": ("Right-wing", "3", "False", "False", "", ""),
"HV083": ("", "3", "True", "False", "", ""),
"HV084": ("", "2", "True", "False", "", ""),
"HV085": ("Resistance", "2", "False", "False", "", ""),
"HV086": ("", "3", "True", "False", "", ""),
"HV087": ("", "3", "True", "False", "", ""),
"HV088": ("Western", "3", "False", "False", "", ""),
"HV089": ("Resistance", "3", "False", "False", "", ""),
"HV090": ("Left-wing", "3", "False", "False", "", ""),
"HV091": ("", "2", "True", "False", "", ""),
"HV092": ("Russian", "3", "False", "False", "", ""),
"HV093": ("Right-wing", "3", "False", "False", "", ""),
"HV094": ("Ukrainian", "2", "False", "False", "", ""),
"HV095": ("", "3", "True", "False", "", "User-placeholder only."),
"HV096": ("Ukrainian", "3", "False", "False", "", ""),
"HV097": ("", "3", "True", "False", "", ""),
"HV098": ("Russian", "2", "False", "False", "", ""),
"HV099": ("Right-wing", "3", "False", "False", "", ""),
"HV100": ("Left-wing", "3", "False", "False", "", ""),
"HV101": ("", "3", "True", "False", "", ""),
"HV102": ("Right-wing", "3", "False", "False", "", ""),
"HV103": ("", "2", "True", "False", "", ""),
"HV104": ("", "2", "True", "False", "", ""),
"HV105": ("Left-wing", "3", "False", "False", "", ""),
"HV106": ("", "2", "True", "False", "", ""),
"HV107": ("Russian", "2", "False", "False", "", ""),
"HV108": ("", "3", "True", "False", "", ""),
"HV109": ("Left-wing", "2", "False", "False", "", ""),
"HV110": ("Western", "3", "False", "False", "", ""),
"HV111": ("", "3", "True", "False", "", ""),
"HV112": ("Zionist", "3", "False", "False", "", ""),
"HV113": ("", "3", "True", "False", "", ""),
"HV114": ("Left-wing", "3", "False", "False", "", ""),
"HV115": ("Resistance", "3", "False", "False", "", ""),
"HV116": ("Western", "3", "False", "False", "", ""),
"HV117": ("Right-wing", "3", "False", "False", "", ""),
"HV118": ("Right-wing", "3", "False", "False", "", ""),
"HV119": ("Ukrainian", "3", "False", "False", "", ""),
"HV120": ("Western", "3", "False", "False", "", ""),
"HV121": ("", "3", "True", "False", "", ""),
"HV122": ("Zionist", "2", "False", "False", "", ""),
"HV123": ("", "2", "True", "False", "", ""),
"HV124": ("Resistance", "3", "False", "False", "", ""),
"HV125": ("Right-wing", "3", "False", "False", "", ""),
"HV126": ("Left-wing", "3", "False", "False", "", ""),
"HV127": ("", "3", "True", "False", "", "URL-only row."),
"HV128": ("", "3", "True", "False", "", ""),
"HV129": ("Zionist", "3", "False", "False", "", ""),
"HV130": ("", "2", "True", "False", "", ""),
"HV131": ("Zionist", "2", "False", "False", "", ""),
"HV132": ("Resistance", "2", "False", "False", "", ""),
"HV133": ("Ukrainian", "3", "False", "False", "", ""),
"HV134": ("", "2", "True", "False", "", ""),
"HV135": ("", "3", "True", "False", "", ""),
"HV136": ("Right-wing", "2", "False", "True", "Western", "US homeland-security framing could plausibly fit conservative-populist or broader Western-security framing."),
"HV137": ("Left-wing", "2", "False", "False", "", ""),
"HV138": ("Western", "3", "False", "False", "", ""),
"HV139": ("", "3", "True", "False", "", "Channel-seizure notice; treated as data-quality artifact, not narrative content."),
"HV140": ("", "3", "True", "False", "", ""),
"HV141": ("", "2", "True", "False", "", ""),
"HV142": ("Zionist", "3", "False", "False", "", ""),
"HV143": ("Resistance", "3", "False", "False", "", ""),
"HV144": ("Ukrainian", "3", "False", "False", "", ""),
"HV145": ("Left-wing", "3", "False", "False", "", ""),
"HV146": ("Ukrainian", "2", "False", "False", "", ""),
"HV147": ("", "3", "True", "False", "", ""),
"HV148": ("Zionist", "3", "False", "False", "", ""),
"HV149": ("Resistance", "3", "False", "False", "", ""),
"HV150": ("", "3", "True", "False", "", ""),
"HV151": ("Resistance", "2", "False", "False", "", ""),
"HV152": ("", "2", "True", "False", "", ""),
"HV153": ("", "3", "True", "False", "", ""),
"HV154": ("", "2", "True", "False", "", ""),
"HV155": ("", "3", "True", "False", "", ""),
"HV156": ("Western", "3", "False", "False", "", ""),
"HV157": ("", "3", "True", "False", "", ""),
"HV158": ("Russian", "2", "False", "False", "", ""),
"HV159": ("Zionist", "3", "False", "False", "", ""),
"HV160": ("Ukrainian", "3", "False", "False", "", ""),
"HV161": ("Right-wing", "2", "False", "False", "", ""),
"HV162": ("Russian", "3", "False", "False", "", ""),
"HV163": ("", "2", "True", "False", "", ""),
"HV164": ("Resistance", "3", "False", "False", "", ""),
"HV165": ("Russian", "3", "False", "False", "", ""),
"HV166": ("Left-wing", "2", "False", "False", "", ""),
"HV167": ("Right-wing", "3", "False", "False", "", ""),
"HV168": ("Left-wing", "3", "False", "False", "", ""),
"HV169": ("Western", "2", "False", "True", "Zionist", "Official Western diplomatic framing is primary, with a plausible Zionist security reading."),
"HV170": ("Right-wing", "3", "False", "False", "", ""),
"HV171": ("Resistance", "3", "False", "False", "", ""),
"HV172": ("", "2", "True", "False", "", "Media-dependent fragment with insufficient textual context."),
"HV173": ("", "3", "True", "False", "", ""),
"HV174": ("", "3", "True", "False", "", ""),
"HV175": ("Ukrainian", "3", "False", "False", "", ""),
"HV176": ("Ukrainian", "3", "False", "False", "", ""),
"HV177": ("", "3", "True", "False", "", ""),
"HV178": ("Left-wing", "2", "False", "False", "", ""),
"HV179": ("", "3", "True", "False", "", "Spam/placeholder text."),
"HV180": ("Western", "3", "False", "False", "", ""),
"HV181": ("", "2", "True", "False", "", ""),
"HV182": ("Left-wing", "3", "False", "False", "", ""),
"HV183": ("", "2", "True", "False", "", ""),
"HV184": ("Resistance", "3", "False", "False", "", ""),
"HV185": ("", "3", "True", "False", "", ""),
"HV186": ("Zionist", "3", "False", "False", "", ""),
"HV187": ("Western", "2", "False", "False", "", ""),
"HV188": ("Zionist", "3", "False", "False", "", ""),
"HV189": ("", "2", "True", "False", "", ""),
"HV190": ("Left-wing", "2", "False", "False", "", ""),
"HV191": ("Russian", "3", "False", "False", "", ""),
"HV192": ("Russian", "3", "False", "False", "", ""),
"HV193": ("Right-wing", "3", "False", "False", "", ""),
"HV194": ("", "2", "True", "False", "", ""),
"HV195": ("Ukrainian", "3", "False", "False", "", ""),
"HV196": ("Russian", "3", "False", "False", "", ""),
"HV197": ("Right-wing", "3", "False", "False", "", ""),
"HV198": ("", "2", "True", "False", "", ""),
"HV199": ("", "3", "True", "False", "", ""),
"HV200": ("", "3", "True", "False", "", ""),
"HV201": ("Zionist", "2", "False", "False", "", ""),
"HV202": ("Zionist", "3", "False", "False", "", ""),
"HV203": ("Right-wing", "3", "False", "False", "", ""),
"HV204": ("", "3", "True", "False", "", "Subscription/podcast promotion only."),
"HV205": ("Ukrainian", "3", "False", "False", "", ""),
"HV206": ("Western", "3", "False", "False", "", ""),
"HV207": ("Russian", "3", "False", "False", "", ""),
"HV208": ("Ukrainian", "3", "False", "False", "", ""),
"HV209": ("Zionist", "3", "False", "False", "", ""),
"HV210": ("Western", "3", "False", "False", "", ""),
"HV211": ("Russian", "3", "False", "False", "", ""),
"HV212": ("", "2", "True", "False", "", ""),
"HV213": ("Resistance", "3", "False", "False", "", ""),
"HV214": ("Western", "3", "False", "False", "", ""),
"HV215": ("", "3", "True", "False", "", ""),
"HV216": ("Resistance", "3", "False", "False", "", ""),
"HV217": ("Ukrainian", "3", "False", "False", "", ""),
"HV218": ("Ukrainian", "3", "False", "False", "", ""),
"HV219": ("Resistance", "3", "False", "False", "", ""),
"HV220": ("Right-wing", "3", "False", "False", "", ""),
"HV221": ("Ukrainian", "3", "False", "False", "", ""),
"HV222": ("", "3", "True", "False", "", ""),
"HV223": ("Ukrainian", "3", "False", "False", "", ""),
"HV224": ("Resistance", "3", "False", "False", "", ""),
"HV225": ("", "2", "True", "False", "", ""),
"HV226": ("Russian", "2", "False", "False", "", ""),
"HV227": ("", "3", "True", "False", "", ""),
"HV228": ("Russian", "3", "False", "False", "", ""),
"HV229": ("", "2", "True", "False", "", ""),
"HV230": ("Russian", "3", "False", "False", "", ""),
"HV231": ("", "2", "True", "False", "", ""),
"HV232": ("Left-wing", "3", "False", "False", "", ""),
"HV233": ("", "3", "True", "False", "", "Links/stickers/bots promotion; no narrative content."),
"HV234": ("Right-wing", "3", "False", "False", "", ""),
"HV235": ("", "3", "True", "False", "", ""),
"HV236": ("Zionist", "2", "False", "False", "", ""),
"HV237": ("Right-wing", "3", "False", "False", "", ""),
"HV238": ("Ukrainian", "3", "False", "False", "", ""),
"HV239": ("Zionist", "2", "False", "False", "", ""),
"HV240": ("Resistance", "3", "False", "False", "", ""),
"HV241": ("", "2", "True", "False", "", ""),
"HV242": ("", "3", "True", "False", "", ""),
"HV243": ("", "3", "True", "False", "", "Channel-seizure notice; treated as data-quality artifact, not narrative content."),
"HV244": ("", "3", "True", "False", "", ""),
"HV245": ("Left-wing", "3", "False", "False", "", ""),
"HV246": ("Resistance", "3", "False", "False", "", ""),
"HV247": ("Western", "3", "False", "False", "", ""),
"HV248": ("", "2", "True", "False", "", "Context-dependent fragment; insufficient information to identify a narrative."),
"HV249": ("", "2", "True", "False", "", ""),
"HV250": ("Zionist", "2", "False", "True", "Right-wing", "Defense against antisemitic/Israel-control conspiracy framing; plausible conservative overlap."),
"HV251": ("Right-wing", "3", "False", "False", "", ""),
"HV252": ("Resistance", "3", "False", "False", "", ""),
"HV253": ("", "2", "True", "False", "", ""),
"HV254": ("Western", "3", "False", "False", "", ""),
"HV255": ("", "3", "True", "False", "", ""),
"HV256": ("", "3", "True", "False", "", ""),
"HV257": ("", "2", "True", "False", "", ""),
"HV258": ("Right-wing", "3", "False", "False", "", ""),
"HV259": ("", "3", "True", "False", "", ""),
"HV260": ("Right-wing", "3", "False", "False", "", ""),
"HV261": ("Zionist", "3", "False", "False", "", ""),
"HV262": ("Right-wing", "3", "False", "False", "", ""),
"HV263": ("Left-wing", "3", "False", "False", "", ""),
"HV264": ("", "3", "True", "False", "", "First-post placeholder; no narrative content."),
"HV265": ("Western", "2", "False", "False", "", ""),
"HV266": ("Ukrainian", "2", "False", "False", "", ""),
"HV267": ("", "3", "True", "False", "", ""),
"HV268": ("Resistance", "2", "False", "False", "", ""),
"HV269": ("Ukrainian", "3", "False", "False", "", ""),
"HV270": ("Left-wing", "3", "False", "False", "", ""),
"HV271": ("Right-wing", "2", "False", "True", "Zionist", "Pro-Trump framing is primary; claim also strongly supports an Israeli-security reading."),
"HV272": ("Russian", "2", "False", "False", "", ""),
"HV273": ("Left-wing", "3", "False", "False", "", ""),
"HV274": ("Western", "2", "False", "False", "", ""),
"HV275": ("Ukrainian", "3", "False", "False", "", ""),
"HV276": ("Western", "3", "False", "False", "", ""),
"HV277": ("", "3", "True", "False", "", ""),
"HV278": ("", "3", "True", "False", "", ""),
"HV279": ("", "3", "True", "False", "", "No substantive narrative content."),
"HV280": ("Western", "2", "False", "False", "", ""),
"HV281": ("", "3", "True", "False", "", ""),
"HV282": ("Resistance", "3", "False", "False", "", ""),
"HV283": ("Ukrainian", "3", "False", "False", "", ""),
"HV284": ("Russian", "3", "False", "False", "", ""),
"HV285": ("Western", "2", "False", "False", "", ""),
"HV286": ("Western", "3", "False", "False", "", ""),
"HV287": ("Russian", "3", "False", "False", "", ""),
"HV288": ("", "2", "True", "False", "", ""),
"HV289": ("Resistance", "3", "False", "False", "", ""),
"HV290": ("Resistance", "3", "False", "False", "", ""),
"HV291": ("", "3", "True", "False", "", ""),
"HV292": ("Left-wing", "3", "False", "False", "", ""),
"HV293": ("Resistance", "3", "False", "False", "", ""),
"HV294": ("Ukrainian", "3", "False", "False", "", ""),
"HV295": ("Russian", "3", "False", "False", "", ""),
"HV296": ("Right-wing", "3", "False", "False", "", ""),
"HV297": ("Russian", "3", "False", "False", "", ""),
"HV298": ("Western", "3", "False", "False", "", ""),
"HV299": ("Left-wing", "2", "False", "False", "", ""),
"HV300": ("Zionist", "3", "False", "False", "", ""),
}

assert len(ANNOTATIONS) == 300, f"Expected 300 entries, got {len(ANNOTATIONS)}"
expected_ids = {f"HV{i:03d}" for i in range(1, 301)}
assert set(ANNOTATIONS.keys()) == expected_ids, "ID set mismatch"

in_path = f"{BASE}\\human_validation_pilot_300_blind.csv"
out_path = f"{BASE}\\human_validation_pilot_300_blind.csv"  # overwrite canonical file

with open(in_path, newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    rows = list(reader)

assert fieldnames == [
    "annotation_id", "text", "reviewer_label", "confidence",
    "neutral_or_no_clear_narrative", "ambiguous_flag",
    "secondary_narrative", "notes",
], f"Unexpected columns: {fieldnames}"

updated = 0
for row in rows:
    aid = row["annotation_id"]
    label, conf, neutral, amb, sec, notes = ANNOTATIONS[aid]
    row["reviewer_label"] = label
    row["confidence"] = conf
    row["neutral_or_no_clear_narrative"] = neutral
    row["ambiguous_flag"] = amb
    row["secondary_narrative"] = sec
    row["notes"] = notes
    updated += 1

assert updated == 300

with open(out_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

print(f"Merged {updated} annotation rows into {out_path}")
